[tasks.install-solana]
condition = { files_not_exist = ["${HOME}/.local/share/solana/install/active_release/bin/solana"] }
script = 'sh -c "$(curl -sSfL https://release.solana.com/v1.14.5/install)"'
env = { PATH = "${HOME}/.local/share/solana/install/active_release/bin:${PATH}" }

[tasks.test]
dependencies = ["install-solana"]

[tasks.build]
dependencies = ["install-solana"]

[tasks.ci-flow]
dependencies = [
    "print-cargo-make-env",
    "print-project-env",
    "print-ci-env",
    "print-git-env",
    "print-rust-env",
    "print-cargo-env",
    "print-crate-env",

    "check-format",
    "check",
    "clippy",
    "build",
    "test",
]
