name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get clean && sudo apt-get update
        sudo apt-get install -y pkg-config libudev-dev
    - name: Install stable rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Install nightly rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        components: rustfmt
    - name: Install cargo-make
      uses: davidB/rust-cargo-make@v1
    - name: Run CI
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: ci-flow
